### ISSUE TITLE
Impossible d'activer dedipass

### ISSUE THREAD

**Issue by AzhukOffi** [MineWeb/Plugin-Shop#14]
Bonjour, 
je n'arrive pas a activé le paiement via dedipass ça me et bien "Succès : Vous avez bien activé Dédipass comme mode de paiement !" mais le bouton activé reste là et impossible de payé avec

**Comment by Eywek** [comment]
Tu peux me faire un screen de la table shop__dedipass_configs dans ta base de données ?

**Comment by CryLegende** [comment]
Sa m'était déjà arriver plusieurs fois.
Quand c'était comme sa j'avais réglé le problème en réinstallant le plugin shop.

**Comment by Azrty** [comment]
Il t’as demandé une screen de ta table shop__dedipass_configs dans ta base de données, pas tes antérieures solutions qui ne sont justement qu’antérieures !

**Comment by Azrty** [comment]
@CryLegende Il t’as demandé une screen de ta table shop__dedipass_configs dans ta base de données, pas tes antérieures solutions qui ne sont justement qu’antérieures !

**Comment by CryLegende** [comment]
@Azrty Déjà calme toi, si tu regarde bien se n'est pas a moi qui parle et si j'ai dit sa c'est pour aider.

**Comment by AzhukOffi** [comment]
Le bug a été résolu après la maj du plugin shop

**Comment by Azrty** [comment]
Ah désolé @CryLegende, merci de me l’avoir dit, j’penses que je vais arrêter de répondre aux issues à 1h du mat (qc)

**Comment by CryLegende** [comment]
Pas grave tkt @Azrty ;)
