### ISSUE TITLE
Problème affichage boutique dédipass

### ISSUE THREAD

**Issue by MrAnthonyPvP** [MineWeb/Plugin-Shop#16]
Bonjour,
Mon dédipass marcher très bien jusqu’à maintenant il a décidé de ne plus s'affichez dans la boutique, quand nous voulons créditer nos comptes, il n'est plus affichez alors que je beau l'activé .

Succès : Vous avez bien activé Dédipass comme mode de paiement !

http://image.noelshack.com/fichiers/2018/22/6/1527954298-shop-dedipass-config.png
log - error.log : https://privatebin.franceserv.fr/?2f90aed03321ff35#H7Cg30Yt6wWXxQTEAfH6eTCy+7+rf3EtVi5juiwn4k4=

**Comment by Eywek** [comment]
Il manque le champs `status` dans la table `shop__dedipass_configs` (cf. https://github.com/MineWeb/Plugin-Shop/blob/master/SQL/schema.php#L25)

**Comment by MrAnthonyPvP** [comment]
Et je vais ou pour modifier cela ? s'il vous plaît ? merci.

**Comment by Eywek** [comment]
Dans la base de données, dans la table `shop__dedipass_configs` il faut modifier la structure et ajouter le champ manquant, un tinyint de 1 comme l'indique mon lien.

**Comment by MrAnthonyPvP** [comment]
D'accord merci beaucoup, j'ai réussi : http://image.noelshack.com/fichiers/2018/22/6/1527959558-shop-dedipass-config.png et j'ai videz les caches et sa sais remis :) merci ! 👍 :1st_place_medal:

**Comment by Eywek** [comment]
Parfait ;)
