### ISSUE TITLE
[Suggestion] Sous-catégories

### ISSUE THREAD

**Issue by ZeProf2Code** [MineWeb/Plugin-Shop#29]
Bonjour/Bonsoir, est-il possible d'ajouter des sous-catégories dans la Boutique ?

Cordialement,
ZeProf2Coding

**Comment by KuroSenseii** [comment]
tout est possible mais pas de base, tu devra coder toi meme la modif ou demander a un dev

**Comment by nivcoo** [comment]
Ca arrive dans pas longtemps mais faudra que le thème soit compatible.

**Comment by nivcoo** [comment]
C'est déjà mis en place :p
