### ISSUE TITLE
Comment on installe le plugin ?

### ISSUE THREAD

**Issue by ClementGuerin** [MineWeb/Plugin-Shop#5]
J'ai beau regarder le readme, c'est fou je ne vois pas comment on installe le plugin. :^)

**Comment by Melowelei** [comment]
Tu n'arrives pas l'installer via le panel admin (TonSite/admin/plugin) ?

**Comment by ClementGuerin** [comment]
Monsieur n'a pas compris la subtilité de cette issue, en gros Eywek doit fournir une doc sur chaque repo, c'est pas propre là

**Comment by Melowelei** [comment]
**https://github.com/MineWeb/Plugin-Shop/pull/6**
