### ISSUE TITLE
Envoyer des points boutiques à une seule personne 

### ISSUE THREAD

**Issue by Azerosse** [MineWeb/Plugin-Shop#53]
Bonjour est -il possible avec ce plugin d'envoyer des points à une seul personne par exemple il y a l'option cadeau pour envoyer a tous les utilisateurs du site cependant si en tant qu'administrateur je souhaite me donner des points boutique ou en donner à d'autre personnes comment puis-je faire ?

**Comment by nivcoo** [comment]
Via l’édition des USERS
