### ISSUE TITLE
luckperms

### ISSUE THREAD

**Issue by Bobbbe** [MineWeb/Plugin-Shop#60]
pour l'achat de grade dans la boutique, je met ceci comme commande - lp user {player} parent addtemp Matelot 30d  et dans la console ca me dit ceci - [LP] {player} n'est pas un pseudo/uuid valide.
le placeholder pour le joueur ne semble pas etre bon. vous aurriez la bonne commande ? ou le bon placeholder defenissant le joueur avec le plugin luckperms

**Comment by Eywek** [comment]
C'est `{PLAYER}`
