### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Douwdy** [MineWeb/Plugin-Shop#68]
Hi ! Is that possible to add a compatibility with https://stripe.com/ as payment system ?

**Comment by nivcoo** [comment]
I have already do that for my website : https://edensky.fr si i can add that easily.

**Comment by Douwdy** [comment]
how can i add it ?

**Comment by nivcoo** [comment]
You cant

**Comment by Douwdy** [comment]
Stripe payment system will be added soon ?
