### ISSUE TITLE
erreur sur les maj via panel

### ISSUE THREAD

**Issue by KuroSenseii** [MineWeb/Plugin-Shop#7]
Erreur : Le plugin ne peut pas être installé/mis à jour car le CMS ne dispose pas des droits d'écriture dans le dossier /app/Plugin/ (775 ou 755).

alors que le dossier a les perm et que pour le plugin forum sa a marcher

**Comment by Eywek** [comment]
Corrigé avec https://github.com/MineWeb/MineWebCMS/releases/tag/v1.5.2
